### ISSUE TITLE
Sidebar background

### ISSUE THREAD

**Issue by pmsaue0** [01010101lzy/mihari#1]
Hi, 

Could you make the sidebar background color a bit darker so that it can be distinguished from the code editor body?

This is a very nice simple theme.  Thank you for sharing it.

**Comment by lynzrand** [comment]
Sure, will fix that in a few days.

In fact I used the same background color for sidebar and code editor intentionally to make a "unibody" feel, but you got the point here. Using different color for these parts do improve usability.

Thanks for supporting!

**Comment by pmsaue0** [comment]
Thanks! 

I do think the unibody feel is pretty interesting -- I haven't seen other themes do that; but it makes resizing the sidebar kind of tricky (and I end up doing that pretty often)

**Comment by lynzrand** [comment]
Okay I'm editing this color right now, and I ran into a design problem. Should I _just_ darken the sidebar, or should I darken everything except the editor?

Screenshots for comparison:

![图片](https://user-images.githubusercontent.com/10259119/61773695-e591b580-ae27-11e9-83fa-d0bcf4644e44.png)

^ Darkening everything except editor

![图片](https://user-images.githubusercontent.com/10259119/61770361-a3647600-ae1f-11e9-8d48-1043ebf4a4e9.png)

^ Only darkening sidebar, activity bar and status bar

![图片](https://user-images.githubusercontent.com/10259119/61770481-ecb4c580-ae1f-11e9-89e6-5ddff0b286c8.png)

^ Only darkening sidebar and activity bar

---

Also, for the "unibody" thing, I personally use the "Ayu Mirage" theme as a daily driver and it managed to have a great unified look. It looks like this:

![图片](https://user-images.githubusercontent.com/10259119/61770569-2b4a8000-ae20-11e9-8b34-7af241988de6.png)

---

edit: changed the first screenshot to add darkening on inactive tabs (similar to "Ayu Mirage" theme)

**Comment by pmsaue0** [comment]
I think darkening both the sidebar and the terminal is best.  But I also think that you should make something that you personally really enjoy :)  I could fork the repo and make a version that had these changes.  Perhaps the best solution, if possible, is to create a json option in the theme to choose either "unibody" or "paneled"

**Comment by lynzrand** [comment]
Fixed in latest commit. The original theme is "unchanged" (actually with minor changes) with the same name, and the one you asked for is at "Mihari Bordered" theme. 

New version is live at VS Marketplace.

Thanks again for supporting!

**Comment by pmsaue0** [comment]
Wonderful!  I'm using it now :) 

It's a great theme.  I do use Mahiro on occasion when I am in a very bright place, too, so adding a "Mahiro Bordered" option there would be appreciated as well.  

Thank you!
